version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: football-manager-app
    command: ./mvnw spring-boot:run
    volumes:
      - .:/app
